### DISCUSSION TITLE
Which schema to select for tamasfe.even-better-toml?

### DISCUSSION THREAD

**Discussion by dionysuzx** [paulrberg/foundry-template#20] [Q&A]
I am using the recommended TOML formatter from `settings.json`. However, it seems you need to select a schema, otherwise it says "no schema selected" in the bottom right. It still formats without a schema and gives me syntax highlighting, but it doesn't "indent" like the `foundry.toml` which is shown in the template repo.

what i mean is it looks like:
```
[fmt]
line_length = 100
```

instead of
```
[fmt]
  line_length = 100
```

Is there any configuration in order to get this type of indentation formatting with the extension?

**Comment by PaulRBerg** [comment]
Hah, this is interesting! This is the first them I hear about schemas for [tamasfe.even-better-toml](https://marketplace.visualstudio.com/items?itemName=tamasfe.even-better-toml). I also see "no schema selected" in my local VSCode set-up, but formatting works as expected, i.e., I get those four spaces as indenting.

Most users of this template don't have this issue (I talked to many of them personally, and they would have told me if this was an issue), so do you have another extension that blocks the formatting? Here are two suggestions:

- Do you have a global `editor.defaultFormatter`? If yes, can you try disabling it?
- Can you try disabling [all installed extensions](https://code.visualstudio.com/docs/editor/extension-marketplace#_disable-an-extension), and then re-enable the Taplo extension?

**Reply by dionysuzx** [reply]
> Do you have a global editor.defaultFormatter? If yes, can you try disabling it?

I did not, so didn't do anything here.

> Can you try disabling [all installed extensions](https://code.visualstudio.com/docs/editor/extension-marketplace#_disable-an-extension), and then re-enable the Taplo extension?

I did this, but ran into the same issue (no four space indent).

> I also see "no schema selected" in my local VSCode set-up

Gotchya! Yeah I also have it as "no schema selected" now too.

---

It's definitely doing *something* (if i add some arbitrary whitespace for example `{ access = "read", path = "./out" },` -> `{access = "read", path ="./out" },` then it will fix it! But it seems to be incomplete.. because I am missing those indents.

If you were to use my exact `foundry.toml`, would it reproduce or indent it properly? Here it is:
```
# See more config options https://github.com/foundry-rs/foundry/tree/master/config
[profile.default]
solc-version = "0.8.18"
src = 'contracts'
out = 'out'
test = 'test'
libs = ['lib']
gas_price = 10000000000            # gas price is 10 Gwei
optimizer = true
optimizer_runs = 200
ffi = true
gas_limit = '18446744073709551615'
memory_limit = 2073741824

# Do not change the block_gas_limit value, TaikoL2.t.sol depends on it.
block_gas_limit = 30000000 #30M
# For mainnet_mock tokenomics test we need a huge value to run lots of iterations.
# Use the above 30M for TaikoL2.t.sol related tests, only use this number with mainnet simulation.
#block_gas_limit = 3000000000 #3000M


fs_permissions = [
  { access = "read", path = "./out" },
  { access = "read-write", path = "./deployments" },
  { access = "read", path = "./test" },
]

fuzz = { runs = 256 }

[fmt]
line_length = 100
```

**Reply by PaulRBerg** [reply]
I have used your exact `foundry.toml` content and it got formatted like this:

<details><summary>Details</summary>
<p>

```toml
# See more config options https://github.com/foundry-rs/foundry/tree/master/config
[profile.default]
  solc-version = "0.8.18"
  src = 'contracts'
  out = 'out'
  test = 'test'
  libs = ['lib']
  gas_price = 10000000000            # gas price is 10 Gwei
  optimizer = true
  optimizer_runs = 200
  ffi = true
  gas_limit = '18446744073709551615'
  memory_limit = 2073741824

  # Do not change the block_gas_limit value, TaikoL2.t.sol depends on it.
  block_gas_limit = 30000000 #30M
  # For mainnet_mock tokenomics test we need a huge value to run lots of iterations.
  # Use the above 30M for TaikoL2.t.sol related tests, only use this number with mainnet simulation.
  #block_gas_limit = 3000000000 #3000M


  fs_permissions = [
    { access = "read", path = "./out" },
    { access = "read-write", path = "./deployments" },
    { access = "read", path = "./test" },
  ]

  fuzz = { runs = 256 }

[fmt]
  line_length = 100
```

</p>
</details> 

What's more - I have disabled all of my global extensions, re-enabled Taplo, and the four-space indent still worked. Thus, this looks like an issue with your local set-up.

Are you, by chance, using [EditorConfig](https://editorconfig.org/)?
